version: '3.1'

services:
  app:
    image: go-bookstore
    restart: always
    ports:
      - "9010:9010"
    depends_on:
      - "db"
  db:
    image: mysql:8.0.25
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_USER: spxUsr
      MYSQL_PASSWORD: vqkWWHptpCwmkgDw8twQuExC
      MYSQL_ROOT_PASSWORD: vqkWWHptpCwmkgDw8twQuExC
      MYSQL_DATABASE: go-bookstore