version: '3.9'

services:
  app:
    image: go-bookstore
    container_name: app
    restart: always
    ports:
      - "${APP_HOST_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - "${DB_HOST}"
  db:
    image: mysql:8.0.25
    container_name: ${DB_HOST}
    restart: always
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    env_file:
      - .env
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}