version: '3.9'

services:
  app:
    image: go-bookstore
    container_name: app
    restart: always
    ports:
      - "9010:9010"
    env_file:
      - .env
    depends_on:
      - "db"
  db:
    image: mysql:8.0.25
    container_name: db
    restart: always
    ports:
      - "3308:${DB_PORT}"
    env_file:
      - .env
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}